bot:
  # REQUIRED
  # Telegram papa (private chat) ID
  papa_id: 1234567890
  # OPTIONAL
  # API URL
  # Default: https://api.telegram.org
  api_url: https://api.telegram.org
  # OPTIONAL
  # Credentials directory
  # Default: ./creds
  creds_dir: ./creds
  # OPTIONAL
  # Downloads directory
  # Default: ./downloads
  downloads_dir: ./downloads
  # OPTIONAL
  # Socks5 proxy
  # Ignored if both port and host are not set or are empty
  proxy:
    # OPTIONAL
    # Required if port is set
    host: ""
    # OPTIONAL
    # Required if host is set
    port: 0
    # OPTIONAL
    username: ""
    # OPTIONAL
    password: ""

log:
  # OPTIONAL
  # One of: debug, info, warn, error, fatal, panic
  # Default: info
  level: info
  # OPTIONAL
  # One of: json, pretty
  # Default: pretty
  format: pretty

tidal:
  download:
    # Download timeout durations in seconds
    timeouts:
      # OPTIONAL
      # Default: 2
      get_track_credits: 2
      # OPTIONAL
      # Default: 2
      get_track_lyrics: 2
      # OPTIONAL
      # Default: 10
      download_cover: 10
      # OPTIONAL
      # Default: 2
      get_album_info: 2
      # OPTIONAL
      # Default: 2
      get_stream_urls: 2
      # OPTIONAL
      # Default: 2
      get_playlist_info: 2
      # OPTIONAL
      # Default: 2
      get_mix_info: 2
      # OPTIONAL
      # Default: 2
      get_paged_tracks: 2
      # OPTIONAL
      # Default: 60
      download_dash_segment: 60
      # OPTIONAL
      # Default: 5
      get_vnd_track_file_size: 5
      # OPTIONAL
      # Default: 60
      download_vnd_segment: 60

    concurrency:
      # OPTIONAL
      # Number of album tracks to download concurrently
      # Default: 20
      album_tracks: 20
      # OPTIONAL
      # Number of playlist tracks to download concurrently
      # Default: 20
      playlist_tracks: 20
      # OPTIONAL
      # Number of mix tracks to download concurrently
      # Default: 20
      mix_tracks: 20
      # OPTIONAL
      # Number of VND track parts to download concurrently
      # Default: 5
      vnd_track_parts: 5

telegram:
  # REQUIRED
  # Telegram app ID (see https://my.telegram.org/apps)
  app_id: 1234567890
  # REQUIRED
  # Telegram app hash (see https://my.telegram.org/apps)
  app_hash: "1234567890"
  # OPTIONAL
  # Telegram storage path
  # Default: ./telegram.db
  storage:
    path: ./telegram.db

  upload:
    # OPTIONAL
    # Default: 8
    threads: 8
    # OPTIONAL
    # Default: 8
    pool_size: 8
    # OPTIONAL
    # Default: 4
    limit: 4
    # OPTIONAL
    # Default: 1s
    pause_duration: 1s
    # OPTIONAL
    # Signature to be added to the end of the caption in Telegram-flavored HTML format.
    # See:
    #   https://core.telegram.org/bots/api#html-style
    #   https://core.telegram.org/api/entities#allowed-entities
    signature: |-


      <i>@itsxeptore</i>
    # REQUIRED
    # Telegram peer to upload to
    peer:
      # REQUIRED
      # Telegram peer ID
      id: 1234567890
      # REQUIRED
      # Telegram peer kind
      # One of: user, chat
      kind: user

  # OPTIONAL
  # Socks5 proxy
  # Ignored if both port and host are not set or are empty
  proxy:
    # OPTIONAL
    # Required if port is set
    host: ""
    # OPTIONAL
    # Required if host is set
    port: 0
    # OPTIONAL
    username: ""
    # OPTIONAL
    password: ""
